# Generated by Django 3.1.2 on 2020-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201027_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
